default:

    redirect:
        module: default
        controller: index
        action: index
        
    layout: 
        layout: login
        contentKey: content
                    
production:
    _extends: default

staging:
    _extends: default

testing:
    _extends: default

development:
    _extends: default