default:
    resources:
        contexts:
            - html
            - json
            - html-json

production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default
        
        