default:
    resources:
        error:
            class: Zend_Controller_Plugin_ErrorHandler
            options:
                module: error
                controller: error
                action: error

production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default