default:

    filters:
        id:
            - Int
        departamentId:
            - Int
        name:
            - 
                - Alpha
                - 
                    allowWhiteSpace: true
            - StringToLower
            - UpperWords
            - LowerNamePreposition

    validators:
        id:
            - NotEmpty
            - Int
        departamentId:
            - NotEmpty
            - Int
            -
                - Entity_Exists
                -
                    entity: departament
                    field: id
                    module: example
        name:
            - NotEmpty
            -
                - Alpha
                - 
                    allowWhiteSpace: true
            -
                - StringLength
                -
                    - 3
                    - 128
            -
                - Entity_NotExists
                -
                    entity: account
                    field: name
                    module: example

production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default