default:
    resources:
        dao:
            source: Db_Table
production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default