default:
    resources:
        locale:
            default: pt_BR
            force: true
        
production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default