default:
#    resources:
#        responsecompress:
#            compression: 1


production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default