default:
    resources:
        router:
            routes:
                www:
                    type: Zend_Controller_Router_Route_Hostname
                    route: www.example.com
                    chains:
                        hello:
                            route: helloWorld/:id/*
                            defaults:
                                module: Example
                                controller: Example
                                action: hello
                                
                helloWorld:
                    type: Zend_Controller_Router_Route
                    route: helloWorld
                    defaults:
                        module: example
                        controller: example
                        action: hello
        
production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default