default:
    redirect:
        module: appointment
        controller: treatment
        action: grid
                    
production:
    _extends: default

staging:
    _extends: default

testing:
    _extends: default

development:
    _extends: default