default:

    dojo:
        requiremodules:
           - dijit.TitlePane
            
#    contexts:
#        - json
#        - html
#        - html-json
    
production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default