default:
    redirect:
        module: email
        controller: email
        action: insert
                    
production:
    _extends: default

staging:
    _extends: default

testing:
    _extends: default

development:
    _extends: default