default:
    resources:
        dojo:
            stylesheetmodules:
                - dijit.themes.claro
            modulepaths:
                dojotop: BASE_URLthemes/dojotop/extras/dojo/1.6/dojotop

production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default