default:
    resources:
        theme:
            parents:
              - dojo
        
production:
    _extends: default

staging:
    _extends: default
 
testing:
    _extends: default

development:
    _extends: default